function survival_fraction(xpt1, exp1,Lf)
%CREATEFIGURE(xpt1, exp1)
%  XPT1:  vector of plot x data
%  EXP1:  vector of plot y data

%  Auto-generated by MATLAB on 08-Aug-2023 12:35:03

% Create figure
figure('Color',[1 1 1]);

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create plot
plot(xpt1,exp1,'DisplayName',['Ab - Lip: ',num2str((1-Lf)*60), ' nM - ', num2str(Lf*60), ' nM'],...
    'MarkerIndices',[1 11 21 31 41 51 61 71 81 91],...
    'MarkerSize',8,...
    'Marker','diamond',...
    'LineWidth',2);

% Create ylabel
ylabel('SF (\%)','Interpreter','latex');

% Create xlabel
xlabel('distance from spheroid center ($\mu m$)','Interpreter','latex');

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 100]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',34);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Interpreter','latex');

